name: Dependencies

on:
  # Trigger the workflow on push or pull request
  push:
    branches:
      - main # Trigger on push events to the main branch
      - beta # Trigger on push events to the beta branch
  pull_request:
    branches:
      - main # Trigger on pull request events targeting the main branch
      - beta # Trigger on pull request events targeting the beta branch
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  check:
    name: Run Check
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: false

      - name: Set up Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm ci

      - name: depcruise
        run: npm run depcruise
