name: Deploy Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    #if: github.repository == 'despair-games/poketernity'
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: "recursive"
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
      - name: Set up SSH
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/*
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy build on server
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: |
          rsync --del --no-times --checksum -vrm dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DESTINATION_DIR }}
          ssh -t ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "~/prmanifest --inpath ${{ secrets.DESTINATION_DIR }} --outpath ${{ secrets.DESTINATION_DIR }}/manifest.json"
      - name: Purge Cloudflare Cache
        if: github.event_name == 'push' && github.ref_name == 'main'
        id: purge-cache
        uses: NathanVaughn/actions-cloudflare-purge@db8c58f61ba4c3ec77229c8fa14ddebb3b59932f # v3.1.0
        with:
          cf_auth: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          files: |
            https://poketernity.com/
            https://poketernity.com/index.html
            https://poketernity.com/manifest.json
            https://poketernity.com/manifest.webmanifest
            https://poketernity.com/service-worker.js
